import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  concepts: [{ type: 'autogenerated', dirName: 'concepts' }],
  // userGuides: [{
  //   type: 'autogenerated', dirName: 'user-guides', 
  // }],
  protocol: [{ type: 'autogenerated', dirName: 'protocol' }],

};

export default sidebars;
